import {Locator, Page} from "@playwright/test";
import {BasePage} from "./base.page";
import {lookup} from "node:dns";

export class RegisterPage extends BasePage {
    readonly titleOfPage: Locator;
    readonly firstNameLabel: Locator;
    readonly firstNameField: Locator;
    readonly firstNameErrorMsg: Locator;
    readonly lastNameLabel: Locator;
    readonly lastNameField: Locator;
    readonly lastNameErrorMsg: Locator;
    readonly dateOfBirthLabel: Locator;
    readonly dateOfBirthField: Locator;
    readonly dateOfBirthErrorMsg: Locator;
    readonly streetLabel: Locator;
    readonly streetField: Locator;
    readonly streetErrorMsg: Locator;
    readonly postalCodeLabel: Locator;
    readonly postalCodeField: Locator;
    readonly postalCodeErrorMsg: Locator;
    readonly cityLabel: Locator;
    readonly cityField: Locator;
    readonly cityErrorMsg: Locator;
    readonly stateLabel: Locator;
    readonly stateField: Locator;
    readonly stateErrorMsg: Locator;
    readonly countryLabel: Locator;
    readonly countryField: Locator;
    readonly countryErrorMsg: Locator;
    readonly phoneLabel: Locator;
    readonly phoneField: Locator;
    readonly phoneErrorMsg: Locator;
    readonly emailLabel: Locator;
    readonly emailField: Locator;
    readonly emailErrorMsg: Locator;
    readonly passwordLabel: Locator;
    readonly passwordField: Locator;
    readonly passwordErrorMsg: Locator;
    readonly passwordHelp: Locator;
    readonly passwordStrength: Locator;
    readonly strengthLabels: Locator;
    readonly strengthBar: Locator;
    readonly passwordError: Locator;
    readonly registerBtn: Locator;
    readonly passwordEyeBtn: Locator;

    constructor(page: Page) {
        super(page, "https://practicesoftwaretesting.com/auth/register");
        this.titleOfPage = page.getByRole('heading', { name: 'Customer registration', level: 3 });
        this.firstNameLabel = page.locator("app-register[for=first_name]");
        this.firstNameField = page.locator("[data-test=first-name]");
        this.firstNameErrorMsg = page.locator("[data-test=first-name-error]");
        this.lastNameLabel = page.locator("app-register[for=last_name]");
        this.lastNameField = page.locator("[data-test=last-name]");
        this.lastNameErrorMsg = page.locator("[data-test=last-name-error]");
        this.dateOfBirthLabel = page.locator("app-register[for=dob]");
        this.dateOfBirthField = page.locator("[data-test=dob]");
        this.dateOfBirthErrorMsg = page.locator("[data-test=dob-error]");
        this.streetLabel = page.locator("app-register[for=street]");
        this.streetField = page.locator("[data-test=street]");
        this.streetErrorMsg = page.locator("[data-test=street-error]");
        this.postalCodeLabel = page.locator("app-register[for=postal_code]");
        this.postalCodeField = page.locator("[data-test=postal_code]");
        this.postalCodeErrorMsg = page.locator("[data-test=postal_code-error]");
        this.cityLabel = page.locator("app-register[for=city]");
        this.cityField = page.locator("[data-test=city]");
        this.cityErrorMsg = page.locator("[data-test=city-error]");
        this.stateLabel = page.locator("app-register[for=state]");
        this.stateField = page.locator("[data-test=state]");
        this.stateErrorMsg = page.locator("[data-test=state-error]");
        this.countryLabel = page.locator("app-register[for=country]");
        this.countryField = page.locator("[data-test=country]");
        this.countryErrorMsg = page.locator("[data-test=country-error]");
        this.phoneLabel = page.locator("app-register[for=phone]");
        this.phoneField = page.locator("[data-test=phone]");
        this.phoneErrorMsg = page.locator("[data-test=phone-error]");
        this.emailLabel = page.locator("app-register[for=email]");
        this.emailField = page.locator("[data-test=email]");
        this.emailErrorMsg = page.locator("[data-test=email-error]");
        this.passwordLabel = page.locator("app-register[for=password]");
        this.passwordField = page.locator("[data-test=password]");
        this.passwordEyeBtn = page.locator(".input-group-append button");
        this.passwordErrorMsg = page.locator("[data-test=password-error]");
        this.passwordHelp = page.locator("#passwordHelp");
        this.passwordStrength = page.locator(".password-strength.mt-2");
        this.strengthLabels = page.locator(".strength-labels");
        this.strengthBar = page.locator(".strength-bar").locator('div');
        this.passwordError = page.locator("[data-test=password-error]");
        this.registerBtn = page.locator("[data-test=register-submit]");
    }
}
